# Generated by Django 2.1.2 on 2018-11-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181122_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='photo',
            field=models.ImageField(blank=True, default='photo', upload_to='articles'),
        ),
    ]
