# Generated by Django 2.1.2 on 2018-11-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181121_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosample',
            name='user',
        ),
    ]
