# Generated by Django 2.1.2 on 2018-11-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181123_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='photo',
            field=models.ImageField(blank=True, default='photo', null=True, upload_to='articles'),
        ),
    ]
